unpackaged/objects/TTT_Game_Moves__e.object
<CustomObject>
    <description>This will store the moves taken by each players</description>
    <fields>
        <fullName>TTT_Board_Positions__c</fullName>
        <description>This will store the current moves taken by players</description>
        <label>Board Position</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>TTT Game Moves</label>
    <pluralLabel>TTT Game Moves</pluralLabel>
</CustomObject>

unpackaged/classes/TTT_PlayingAreaController.cls
/* 
@Author: Pankaj Agrahari 
@Email: salesforceblue@gmail.com 
@Desc: Controller class for tttPlayingArea lwc 
*/

public with sharing class TTT_PlayingAreaController {

    //@Desc: This will publish the gameMoves. Listening component will read this and will render the latest move on the board(lwc)
    @AuraEnabled    
    public static void publishMove(Object movesData, String gameId, String gameState) {
        // Do a publish call here
        Map<String, Map<String,Object>> mapOfGameIdToGameData = new Map<String, Map<String,Object>>();
        Map<String, Object> mapOfGameData = new Map<String, Object>();
        mapOfGameData.put('Moves', movesData);
        mapOfGameData.put('State', gameState);
        mapOfGameIdToGameData.put(gameId, mapOfGameData);

        Eventbus.publish(new TTT_Game_Moves__e(
            TTT_Board_Positions__c = JSON.serialize(mapOfGameIdToGameData)
        ));

        System.debug('moves published with payload ' + JSON.serialize(mapOfGameIdToGameData));
    }
}