unpackaged/objects/TTT_Game_Area__c.object
<CustomObject>
    <description>This will hold current active game information</description>
    <fields>
        <fullName>TTT_Player_One_Id__c</fullName>
        <description>This is a unique identifier which is a concatenation of user id + lobby id against which user registered</description>
        <label>Player One Unique Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TTT_Player_One__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will hold user id for player one</description>
        <label>Player One</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Game_Area</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TTT_Player_Two_Id__c</fullName>
        <description>This is a unique identifier which is a concatenation of user id + lobby id against which the user registered</description>
        <label>Player Two Unique Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TTT_Player_Two__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will hold user id for player two</description>
        <label>Player Two</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Game_Area1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Game Area</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>Game Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/TTT_Game_Lobby__c.object
<CustomObject>
    <fields>
        <fullName>TTT_Is_Game_Set__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This will inform if there has been an active game set for this player.</description>
        <label>Is Game Set</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TTT_Player__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will hold info for player one</description>
        <label>Player</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Game_Lobby</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Game Lobby</label>
    <nameField>
        <displayFormat>GL-{000}</displayFormat>
        <label>Game Lobby Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Lobby</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/TTT_GameLobbyService.cls
/* 
@Author: Pankaj Agrahari 
@Email: salesforceblue@gmail.com 
@Desc: Service class for GameLobby 
*/

public with sharing class TTT_GameLobbyService {
    /* @Desc: scheduled for Game Area */
    public static void scheduleGame(List<TTT_Game_Lobby__c> recordList) {
        List<TTT_Game_Lobby__c> existingPlayersInLobby = new List<TTT_Game_Lobby__c>();
        List<TTT_Game_Lobby__c> gameLobbyList = new List<TTT_Game_Lobby__c>();
        List<TTT_Game_Lobby__c> lobbyListAddedToGameArea = new List<TTT_Game_Lobby__c>();
        List<TTT_Game_Area__c> gameAreaList = new List<TTT_Game_Area__c>();

        for (TTT_Game_Lobby__c record : [SELECT TTT_Player__c FROM TTT_Game_Lobby__c WHERE ID NOT IN :recordList AND TTT_Is_Game_Set__c = false]) { // Picking existing players awaiting in the lobby
            gameLobbyList.add(record);
        }

        gameLobbyList.addAll(recordList);

        if(gameLobbyList.size() == 1) {return;}

        for(Integer i = 0; i < gameLobbyList.size() - 1; i = i + 2) { 
            if(gameLobbyList[i].TTT_Player__c == gameLobbyList[i+1].TTT_Player__c) continue;
            gameAreaList.add(
                new TTT_Game_Area__c(
                    TTT_Player_One__c = gameLobbyList[i].TTT_Player__c,
                    TTT_Player_One_Id__c = gameLobbyList[i].Id + '__' + gameLobbyList[i].TTT_Player__c,
                    TTT_Player_Two__c = gameLobbyList[i+1].TTT_Player__c,
                    TTT_Player_Two_Id__c = gameLobbyList[i+1].Id + '__' + gameLobbyList[i+1].TTT_Player__c
                )
            );

            lobbyListAddedToGameArea.add(new TTT_Game_Lobby__c(Id = gameLobbyList[i].Id, TTT_Is_Game_Set__c = true));
            lobbyListAddedToGameArea.add(new TTT_Game_Lobby__c(Id = gameLobbyList[i+1].Id, TTT_Is_Game_Set__c = true));
        }   

        if(gameAreaList.isEmpty()) {return;}

        insert gameAreaList; 
        updateGameSetFlagInLobby(lobbyListAddedToGameArea);        

    }

    /* @Desc: set TTT_Is_Game_Set__c flag on lobby once the players are added to the game area */
    public static void updateGameSetFlagInLobby(List<TTT_Game_Lobby__c> recordList) {
        update recordList;
    }

}