unpackaged/objects/TTT_Game_Area__c.object
<CustomObject>
    <description>This will hold current active game information</description>
    <fields>
        <fullName>TTT_Player_One_Id__c</fullName>
        <description>This is a unique identifier which is a concatenation of user id + lobby id against which user registered</description>
        <label>Player One Unique Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TTT_Player_One__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will hold user id for player one</description>
        <label>Player One</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Game_Area</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TTT_Player_Two_Id__c</fullName>
        <description>This is a unique identifier which is a concatenation of user id + lobby id against which the user registered</description>
        <label>Player Two Unique Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TTT_Player_Two__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will hold user id for player two</description>
        <label>Player Two</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Game_Area1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Game Area</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>Game Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/TTT_Game_Start__e.object
<CustomObject>
    <description>This will notify for a started game to the game lobby</description>
    <fields>
        <fullName>TTT_Game_Info__c</fullName>
        <description>This will store the information of games to start</description>
        <label>Game Info</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>TTT Game Start</label>
    <pluralLabel>TTT Game Start</pluralLabel>
</CustomObject>

unpackaged/classes/TTT_GameAreaServiceHelper.cls
/* 
@Author: Pankaj Agrahari 
@Email: salesforceblue@gmail.com 
@Desc: Helper class for TTT_GameAreaService 
*/

public with sharing class TTT_GameAreaServiceHelper {
    
    /* @Desc:  This method will publish the required platform event to start the game */
    public static String preparePayload(List<TTT_Game_Area__c> recordsList) {
        Map<String, String> mapOfGameInfo = new Map<String,String>();
        Map<String, Map<String,String>> mapOfUserIdToGameInfo = new Map<String, Map<String, String>>();

        for(TTT_Game_Area__c currentGame : recordsList) {
            // @note: Storing info for player one
            mapOfGameInfo = new Map<String,String>();
            mapOfGameInfo.put('GameId', currentGame.Id);
            mapOfGameInfo.put('PlayingWith', currentGame.TTT_Player_Two__c);
            mapOfGameInfo.put('PlayingAs', 'X');
            mapOfUserIdToGameInfo.put(currentGame.TTT_Player_One_Id__c, mapOfGameInfo);

            // @note: Storing info for player two
            mapOfGameInfo = new Map<String,String>();
            mapOfGameInfo.put('GameId', currentGame.Id);
            mapOfGameInfo.put('PlayingWith', currentGame.TTT_Player_One__c);
            mapOfGameInfo.put('PlayingAs', 'O');
            mapOfUserIdToGameInfo.put(currentGame.TTT_Player_Two_Id__c, mapOfGameInfo);

        }

        return JSON.serialize(mapOfUserIdToGameInfo);
    }

    /* @Desc:  This method will publish the required platform event to start the game */
    public static void publishCallToStartGame(String payload) {
        Eventbus.publish(new TTT_Game_Start__e(
            TTT_Game_Info__c = payload
        ));
    }

}